import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'React 19 完全指南',
  description: '系统全面的 React 19 开源教程',
  lang: 'zh-CN',
  lastUpdated: true,
  cleanUrls: true,
  head: [
    ['meta', { name: 'theme-color', content: '#61dafb' }],
    ['meta', { name: 'og:type', content: 'website' }],
    ['meta', { name: 'og:title', content: 'React 19 完全指南' }],
  ],
  themeConfig: {
    logo: '/logo.svg',
    siteTitle: 'React 19 完全指南',
    nav: [
      { text: '首页', link: '/' },
      { text: '基础', link: '/Part0-前置基础/00-为什么学习React' },
      { text: '进阶', link: '/Part2-Hooks深入掌握/01-Hooks概述与规则' },
      { text: '面试', link: '/Part17-面试突破/01-Virtual-DOM与Diff算法' },
    ],
    search: {
      provider: 'local'
    },
    sidebar: [
      {
        text: '📖 简介',
        items: [
          { text: '关于本书', link: '/' }
        ]
      },
      {
        text: 'Part 0 - 前置基础',
        collapsed: true,
        items: [
          { text: '为什么学习React', link: '/Part0-前置基础/00-为什么学习React' },
          { text: 'JavaScript ES6+核心语法', link: '/Part0-前置基础/01-JavaScript-ES6+核心语法' },
          { text: '包管理器详解', link: '/Part0-前置基础/02-包管理器详解(npm-yarn-pnpm)' },
          { text: 'Node.js环境配置', link: '/Part0-前置基础/03-Node.js环境配置' },
          { text: 'Git版本控制基础', link: '/Part0-前置基础/04-Git版本控制基础' },
        ]
      },
      {
        text: 'Part 1 - React核心基础',
        collapsed: true,
        items: [
          { text: 'React简介与特点', link: '/Part1-React核心基础/01-React简介与特点' },
          { text: '环境搭建', link: '/Part1-React核心基础/02-环境搭建(Vite-Next.js)' },
          { text: '第一个React应用', link: '/Part1-React核心基础/03-第一个React应用' },
          { text: '项目结构解析', link: '/Part1-React核心基础/04-项目结构解析' },
          { text: 'JSX语法规则', link: '/Part1-React核心基础/05-JSX语法规则' },
          { text: 'JSX表达式与嵌入', link: '/Part1-React核心基础/06-JSX表达式与嵌入' },
          { text: 'JSX与虚拟DOM关系', link: '/Part1-React核心基础/07-JSX与虚拟DOM关系' },
          { text: '函数组件与类组件', link: '/Part1-React核心基础/08-函数组件与类组件' },
          { text: '组件的创建与导出', link: '/Part1-React核心基础/09-组件的创建与导出' },
          { text: '组件的导入与使用', link: '/Part1-React核心基础/10-组件的导入与使用' },
          { text: 'Props基本用法', link: '/Part1-React核心基础/11-Props基本用法' },
          { text: 'Props类型检查', link: '/Part1-React核心基础/12-Props类型检查(PropTypes)' },
          { text: 'Props默认值', link: '/Part1-React核心基础/13-Props默认值' },
          { text: 'Children Props', link: '/Part1-React核心基础/14-Children-Props' },
          { text: 'State概念与使用', link: '/Part1-React核心基础/15-State概念与使用' },
          { text: 'State更新规则', link: '/Part1-React核心基础/16-State更新规则' },
          { text: 'State的不可变性', link: '/Part1-React核心基础/17-State的不可变性' },
          { text: '事件绑定基础', link: '/Part1-React核心基础/18-事件绑定基础' },
          { text: '事件对象与参数传递', link: '/Part1-React核心基础/19-事件对象与参数传递' },
          { text: '合成事件系统', link: '/Part1-React核心基础/20-合成事件系统' },
          { text: 'if-else条件渲染', link: '/Part1-React核心基础/21-if-else条件渲染' },
          { text: '三元运算符渲染', link: '/Part1-React核心基础/22-三元运算符渲染' },
          { text: '逻辑与运算符渲染', link: '/Part1-React核心基础/23-逻辑与运算符渲染' },
          { text: 'map方法渲染列表', link: '/Part1-React核心基础/24-map方法渲染列表' },
          { text: 'Key的作用与优化', link: '/Part1-React核心基础/25-Key的作用与优化' },
          { text: '列表项的增删改', link: '/Part1-React核心基础/26-列表项的增删改' },
          { text: '受控组件详解', link: '/Part1-React核心基础/27-受控组件详解' },
          { text: '非受控组件详解', link: '/Part1-React核心基础/28-非受控组件详解' },
          { text: '多个表单元素处理', link: '/Part1-React核心基础/29-多个表单元素处理' },
          { text: 'Todo应用(基础版)', link: '/Part1-React核心基础/30-Todo应用(基础版)' },
          { text: '计数器应用', link: '/Part1-React核心基础/31-计数器应用' },
          { text: '购物车应用', link: '/Part1-React核心基础/32-购物车应用' },
        ]
      },
      {
        text: 'Part 2 - Hooks深入掌握',
        collapsed: true,
        items: [
          { text: 'Hooks概述与规则', link: '/Part2-Hooks深入掌握/01-Hooks概述与规则' },
          { text: 'useState基础与进阶', link: '/Part2-Hooks深入掌握/02-useState基础与进阶' },
          { text: 'useEffect副作用管理', link: '/Part2-Hooks深入掌握/03-useEffect副作用管理' },
          { text: 'useContext全局状态', link: '/Part2-Hooks深入掌握/04-useContext全局状态' },
          { text: 'useMemo计算缓存', link: '/Part2-Hooks深入掌握/05-useMemo计算缓存' },
          { text: 'useCallback函数缓存', link: '/Part2-Hooks深入掌握/06-useCallback函数缓存' },
          { text: 'React.memo组件缓存', link: '/Part2-Hooks深入掌握/07-React.memo组件缓存' },
          { text: '性能优化实战对比', link: '/Part2-Hooks深入掌握/08-性能优化实战对比' },
          { text: 'useRef DOM引用', link: '/Part2-Hooks深入掌握/09-useRef-DOM引用' },
          { text: 'useRef保存可变值', link: '/Part2-Hooks深入掌握/10-useRef保存可变值' },
          { text: 'forwardRef与useImperativeHandle', link: '/Part2-Hooks深入掌握/11-forwardRef与useImperativeHandle' },
          { text: 'useReducer状态管理', link: '/Part2-Hooks深入掌握/12-useReducer状态管理' },
          { text: 'useReducer与useState对比', link: '/Part2-Hooks深入掌握/13-useReducer与useState对比' },
          { text: 'useReducer实战案例', link: '/Part2-Hooks深入掌握/14-useReducer实战案例' },
          { text: 'useId唯一ID生成', link: '/Part2-Hooks深入掌握/15-useId唯一ID生成' },
          { text: 'useLayoutEffect同步更新', link: '/Part2-Hooks深入掌握/16-useLayoutEffect同步更新' },
          { text: 'useDebugValue自定义调试', link: '/Part2-Hooks深入掌握/17-useDebugValue自定义调试' },
          { text: 'useSyncExternalStore外部状态同步', link: '/Part2-Hooks深入掌握/18-useSyncExternalStore外部状态同步' },
          { text: 'useInsertionEffect CSS-in-JS优化', link: '/Part2-Hooks深入掌握/19-useInsertionEffect-CSS-in-JS优化' },
          { text: 'useEffectEvent非响应式事件', link: '/Part2-Hooks深入掌握/20-useEffectEvent非响应式事件(实验性)' },
          { text: '自定义Hooks基础', link: '/Part2-Hooks深入掌握/20-自定义Hooks基础' },
          { text: '常用自定义Hooks', link: '/Part2-Hooks深入掌握/21-常用自定义Hooks(useLocalStorage-useDebounce等)' },
          { text: '自定义Hooks最佳实践', link: '/Part2-Hooks深入掌握/22-自定义Hooks最佳实践' },
          { text: '自定义Hooks库推荐', link: '/Part2-Hooks深入掌握/23-自定义Hooks库推荐(ahooks-react-use)' },
          { text: 'Hooks链表结构', link: '/Part2-Hooks深入掌握/24-Hooks链表结构' },
          { text: 'Hooks调用顺序原理', link: '/Part2-Hooks深入掌握/25-Hooks调用顺序原理' },
          { text: '闭包陷阱与解决', link: '/Part2-Hooks深入掌握/26-闭包陷阱与解决' },
          { text: '手写useState实现', link: '/Part2-Hooks深入掌握/27-手写useState实现' },
          { text: '手写useEffect实现', link: '/Part2-Hooks深入掌握/28-手写useEffect实现' },
          { text: '手写useMemo和useCallback', link: '/Part2-Hooks深入掌握/29-手写useMemo和useCallback' },
        ]
      },
      {
        text: 'Part 3 - React19核心新特性',
        collapsed: true,
        items: [
          { text: 'use()Hook概述', link: '/Part3-React19核心新特性/01-use()Hook概述' },
          { text: 'use()读取Promise数据', link: '/Part3-React19核心新特性/02-use()读取Promise数据' },
          { text: 'use()读取Context', link: '/Part3-React19核心新特性/03-use()读取Context' },
          { text: 'use()与useEffect对比', link: '/Part3-React19核心新特性/04-use()与useEffect对比' },
          { text: 'use()错误处理机制', link: '/Part3-React19核心新特性/05-use()错误处理机制' },
          { text: 'use()实战案例', link: '/Part3-React19核心新特性/06-use()实战案例' },
          { text: 'Server Components概念', link: '/Part3-React19核心新特性/07-Server-Components概念' },
          { text: 'Server vs Client Components对比', link: '/Part3-React19核心新特性/08-Server-vs-Client-Components对比' },
          { text: 'Server Components数据获取', link: '/Part3-React19核心新特性/09-Server-Components数据获取' },
          { text: 'Server与Client Components交互', link: '/Part3-React19核心新特性/10-Server-Components与Client-Components交互' },
          { text: 'use-server指令详解', link: '/Part3-React19核心新特性/11-use-server指令详解' },
          { text: 'Server Components限制与注意事项', link: '/Part3-React19核心新特性/12-Server-Components限制与注意事项' },
          { text: 'Server Components实战案例', link: '/Part3-React19核心新特性/13-Server-Components实战案例' },
          { text: 'Form Actions概述', link: '/Part3-React19核心新特性/14-Form-Actions概述' },
          { text: 'useActionState详解', link: '/Part3-React19核心新特性/15-useActionState详解' },
          { text: 'useFormStatus表单状态', link: '/Part3-React19核心新特性/16-useFormStatus表单状态' },
          { text: 'Server Actions实现', link: '/Part3-React19核心新特性/17-Server-Actions实现' },
          { text: '表单验证与错误处理', link: '/Part3-React19核心新特性/18-表单验证与错误处理' },
          { text: '渐进增强', link: '/Part3-React19核心新特性/19-渐进增强(Progressive-Enhancement)' },
          { text: 'Form Actions实战案例', link: '/Part3-React19核心新特性/20-Form-Actions实战案例' },
          { text: 'useOptimistic乐观更新', link: '/Part3-React19核心新特性/21-useOptimistic乐观更新' },
          { text: 'useOptimistic与Server Actions配合', link: '/Part3-React19核心新特性/22-useOptimistic与Server-Actions配合' },
          { text: '乐观更新错误回滚', link: '/Part3-React19核心新特性/23-乐观更新错误回滚' },
          { text: 'useOptimistic实战案例', link: '/Part3-React19核心新特性/24-useOptimistic实战案例' },
        ]
      },
      {
        text: 'Part 4 - 并发特性与性能优化',
        collapsed: true,
        items: [
          { text: 'Fiber架构原理', link: '/Part4-并发特性与性能优化/01-Fiber架构原理' },
          { text: '时间切片', link: '/Part4-并发特性与性能优化/02-时间切片(Time-Slicing)' },
          { text: '优先级调度', link: '/Part4-并发特性与性能优化/03-优先级调度(Scheduler)' },
          { text: '双缓冲技术', link: '/Part4-并发特性与性能优化/04-双缓冲技术' },
          { text: '并发模式概述', link: '/Part4-并发特性与性能优化/05-并发模式概述' },
          { text: 'useTransition过渡更新', link: '/Part4-并发特性与性能优化/06-useTransition过渡更新' },
          { text: 'useDeferredValue延迟值', link: '/Part4-并发特性与性能优化/07-useDeferredValue延迟值' },
          { text: 'Suspense基础', link: '/Part4-并发特性与性能优化/08-Suspense基础' },
          { text: 'Suspense数据获取', link: '/Part4-并发特性与性能优化/09-Suspense数据获取' },
          { text: 'Suspense与lazy懒加载', link: '/Part4-并发特性与性能优化/10-Suspense与lazy懒加载' },
          { text: '嵌套Suspense', link: '/Part4-并发特性与性能优化/11-嵌套Suspense' },
          { text: 'Suspense SSR流式渲染', link: '/Part4-并发特性与性能优化/12-Suspense-SSR流式渲染' },
          { text: '错误边界基础', link: '/Part4-并发特性与性能优化/13-错误边界基础' },
          { text: 'getDerivedStateFromError', link: '/Part4-并发特性与性能优化/14-getDerivedStateFromError' },
          { text: 'componentDidCatch', link: '/Part4-并发特性与性能优化/15-componentDidCatch' },
          { text: '错误边界最佳实践', link: '/Part4-并发特性与性能优化/16-错误边界最佳实践' },
          { text: 'react-error-boundary库', link: '/Part4-并发特性与性能优化/17-react-error-boundary库' },
          { text: 'React.memo深入', link: '/Part4-并发特性与性能优化/18-React.memo深入' },
          { text: 'useMemo使用场景', link: '/Part4-并发特性与性能优化/19-useMemo使用场景' },
          { text: 'useCallback使用场景', link: '/Part4-并发特性与性能优化/20-useCallback使用场景' },
          { text: '虚拟列表', link: '/Part4-并发特性与性能优化/21-虚拟列表(react-window-react-virtualized)' },
          { text: '图片懒加载', link: '/Part4-并发特性与性能优化/22-图片懒加载' },
          { text: '代码分割', link: '/Part4-并发特性与性能优化/23-代码分割(lazy-import)' },
          { text: 'Tree-Shaking优化', link: '/Part4-并发特性与性能优化/24-Tree-Shaking优化' },
          { text: 'Bundle体积分析', link: '/Part4-并发特性与性能优化/25-Bundle体积分析' },
          { text: 'React DevTools Profiler', link: '/Part4-并发特性与性能优化/26-React-DevTools-Profiler' },
          { text: 'Chrome Performance面板', link: '/Part4-并发特性与性能优化/27-Chrome-Performance面板' },
          { text: 'Lighthouse性能评分', link: '/Part4-并发特性与性能优化/28-Lighthouse性能评分' },
          { text: 'Web Vitals核心指标', link: '/Part4-并发特性与性能优化/29-Web-Vitals核心指标(LCP-FID-CLS)' },
          { text: '自定义性能监控', link: '/Part4-并发特性与性能优化/30-自定义性能监控' },
          { text: '内存泄漏识别', link: '/Part4-并发特性与性能优化/31-内存泄漏识别' },
          { text: '内存泄漏预防', link: '/Part4-并发特性与性能优化/32-内存泄漏预防' },
          { text: '垃圾回收机制', link: '/Part4-并发特性与性能优化/33-垃圾回收机制' },
        ]
      },
      {
        text: 'Part 5 - 状态管理方案',
        collapsed: true,
        items: [
          { text: 'Context API深入', link: '/Part5-状态管理方案/01-Context-API深入' },
          { text: 'Context性能优化', link: '/Part5-状态管理方案/02-Context性能优化' },
          { text: '多个Context组合模式', link: '/Part5-状态管理方案/03-多个Context组合模式' },
          { text: 'Context与Hooks结合', link: '/Part5-状态管理方案/04-Context与Hooks结合' },
          { text: 'Zustand入门', link: '/Part5-状态管理方案/05-Zustand入门' },
          { text: 'Zustand中间件', link: '/Part5-状态管理方案/06-Zustand中间件' },
          { text: 'Zustand持久化', link: '/Part5-状态管理方案/07-Zustand持久化' },
          { text: 'Zustand DevTools', link: '/Part5-状态管理方案/08-Zustand-DevTools' },
          { text: 'Jotai原子化状态', link: '/Part5-状态管理方案/09-Jotai原子化状态' },
          { text: 'Jotai atoms组合', link: '/Part5-状态管理方案/10-Jotai-atoms组合' },
          { text: 'Jotai异步状态', link: '/Part5-状态管理方案/11-Jotai异步状态' },
          { text: 'Redux核心概念', link: '/Part5-状态管理方案/12-Redux核心概念' },
          { text: 'Redux Toolkit现代Redux', link: '/Part5-状态管理方案/13-Redux-Toolkit现代Redux' },
          { text: 'createSlice创建切片', link: '/Part5-状态管理方案/14-createSlice创建切片' },
          { text: 'RTK Query数据获取', link: '/Part5-状态管理方案/15-RTK-Query数据获取' },
          { text: 'Redux中间件', link: '/Part5-状态管理方案/16-Redux中间件(Thunk-Saga)' },
          { text: 'Valtio代理状态', link: '/Part5-状态管理方案/17-Valtio代理状态' },
          { text: 'Valtio与Zustand对比', link: '/Part5-状态管理方案/18-Valtio与Zustand对比' },
          { text: 'Recoil原子状态', link: '/Part5-状态管理方案/19-Recoil原子状态' },
          { text: 'Recoil选择器', link: '/Part5-状态管理方案/20-Recoil选择器' },
          { text: '状态管理方案对比', link: '/Part5-状态管理方案/21-状态管理方案对比' },
          { text: '如何选择状态管理库', link: '/Part5-状态管理方案/22-如何选择状态管理库' },
          { text: '状态管理最佳实践', link: '/Part5-状态管理方案/23-状态管理最佳实践' },
        ]
      },
      {
        text: 'Part 6 - 路由与导航',
        collapsed: true,
        items: [
          { text: 'React Router v6基础', link: '/Part6-路由与导航/01-React-Router-v6基础' },
          { text: '路由配置与嵌套路由', link: '/Part6-路由与导航/02-路由配置与嵌套路由' },
          { text: '动态路由与参数获取', link: '/Part6-路由与导航/03-动态路由与参数获取' },
          { text: '编程式导航', link: '/Part6-路由与导航/04-编程式导航' },
          { text: '路由守卫与权限控制', link: '/Part6-路由与导航/05-路由守卫与权限控制' },
          { text: 'Loader数据加载', link: '/Part6-路由与导航/06-Loader数据加载' },
          { text: 'Action表单提交', link: '/Part6-路由与导航/07-Action表单提交' },
          { text: 'defer延迟数据加载', link: '/Part6-路由与导航/08-defer延迟数据加载' },
          { text: '路由错误处理', link: '/Part6-路由与导航/09-路由错误处理' },
          { text: 'React Router与Server Components', link: '/Part6-路由与导航/10-React-Router与Server-Components' },
          { text: 'TanStack Router新一代路由', link: '/Part6-路由与导航/11-TanStack-Router新一代路由' },
          { text: '类型安全路由', link: '/Part6-路由与导航/12-类型安全路由' },
        ]
      },
      {
        text: 'Part 7 - 样式解决方案',
        collapsed: true,
        items: [
          { text: '传统CSS导入', link: '/Part7-样式解决方案/01-传统CSS导入' },
          { text: 'CSS Modules模块化', link: '/Part7-样式解决方案/02-CSS-Modules模块化' },
          { text: 'CSS Modules最佳实践', link: '/Part7-样式解决方案/03-CSS-Modules最佳实践' },
          { text: 'Tailwind CSS快速入门', link: '/Part7-样式解决方案/04-Tailwind-CSS快速入门' },
          { text: 'Tailwind配置与自定义', link: '/Part7-样式解决方案/05-Tailwind配置与自定义' },
          { text: 'Tailwind组件库', link: '/Part7-样式解决方案/06-Tailwind组件库(shadcn-ui-daisyUI)' },
          { text: 'Styled Components基础', link: '/Part7-样式解决方案/07-Styled-Components基础' },
          { text: 'Styled Components主题系统', link: '/Part7-样式解决方案/08-Styled-Components主题系统' },
          { text: 'Emotion库使用', link: '/Part7-样式解决方案/09-Emotion库使用' },
          { text: 'CSS-in-JS性能考量', link: '/Part7-样式解决方案/10-CSS-in-JS性能考量' },
          { text: 'UnoCSS即时原子引擎', link: '/Part7-样式解决方案/11-UnoCSS即时原子引擎' },
          { text: '各方案优缺点对比', link: '/Part7-样式解决方案/12-各方案优缺点对比' },
          { text: '样式方案选型指南', link: '/Part7-样式解决方案/13-样式方案选型指南' },
        ]
      },
      {
        text: 'Part 8 - 表单与数据验证',
        collapsed: true,
        items: [
          { text: '受控与非受控组件深入', link: '/Part8-表单与数据验证/01-受控与非受控组件深入' },
          { text: '表单状态管理', link: '/Part8-表单与数据验证/02-表单状态管理' },
          { text: '多步骤表单', link: '/Part8-表单与数据验证/03-多步骤表单' },
          { text: 'React Hook Form入门', link: '/Part8-表单与数据验证/04-React-Hook-Form入门' },
          { text: 'register注册表单', link: '/Part8-表单与数据验证/05-register注册表单' },
          { text: '表单验证规则', link: '/Part8-表单与数据验证/06-表单验证规则' },
          { text: 'Controller受控组件集成', link: '/Part8-表单与数据验证/07-Controller受控组件集成' },
          { text: '表单性能优化', link: '/Part8-表单与数据验证/08-表单性能优化' },
          { text: 'Zod schema验证', link: '/Part8-表单与数据验证/09-Zod-schema验证' },
          { text: 'Yup验证库', link: '/Part8-表单与数据验证/10-Yup验证库' },
          { text: 'Joi验证库', link: '/Part8-表单与数据验证/11-Joi验证库' },
          { text: 'React 19 Form Actions表单', link: '/Part8-表单与数据验证/12-React-19-Form-Actions表单' },
          { text: '表单提交优化', link: '/Part8-表单与数据验证/13-表单提交优化' },
          { text: '文件上传处理', link: '/Part8-表单与数据验证/14-文件上传处理' },
        ]
      },
      {
        text: 'Part 9 - 数据获取策略',
        collapsed: true,
        items: [
          { text: 'Fetch API基础', link: '/Part9-数据获取策略/01-Fetch-API基础' },
          { text: 'Axios封装', link: '/Part9-数据获取策略/02-Axios封装' },
          { text: '错误处理与重试', link: '/Part9-数据获取策略/03-错误处理与重试' },
          { text: 'SWR快速入门', link: '/Part9-数据获取策略/04-SWR快速入门' },
          { text: 'SWR缓存策略', link: '/Part9-数据获取策略/05-SWR缓存策略' },
          { text: 'SWR Mutation变更', link: '/Part9-数据获取策略/06-SWR-Mutation变更' },
          { text: 'SWR乐观更新', link: '/Part9-数据获取策略/07-SWR乐观更新' },
          { text: 'TanStack Query入门', link: '/Part9-数据获取策略/08-TanStack-Query入门' },
          { text: 'useQuery数据查询', link: '/Part9-数据获取策略/09-useQuery数据查询' },
          { text: 'useMutation数据变更', link: '/Part9-数据获取策略/10-useMutation数据变更' },
          { text: '查询缓存管理', link: '/Part9-数据获取策略/11-查询缓存管理' },
          { text: '无限滚动加载', link: '/Part9-数据获取策略/12-无限滚动加载' },
          { text: '离线支持', link: '/Part9-数据获取策略/13-离线支持' },
          { text: 'GraphQL基础', link: '/Part9-数据获取策略/14-GraphQL基础' },
          { text: 'Apollo Client使用', link: '/Part9-数据获取策略/15-Apollo-Client使用' },
          { text: 'GraphQL Codegen代码生成', link: '/Part9-数据获取策略/16-GraphQL-Codegen代码生成' },
          { text: 'tRPC端到端类型安全', link: '/Part9-数据获取策略/17-tRPC端到端类型安全' },
          { text: 'tRPC与React集成', link: '/Part9-数据获取策略/18-tRPC与React集成' },
          { text: '各方案优缺点', link: '/Part9-数据获取策略/19-各方案优缺点' },
          { text: '数据获取最佳实践', link: '/Part9-数据获取策略/20-数据获取最佳实践' },
        ]
      },
      {
        text: 'Part 10 - 动画与交互',
        collapsed: true,
        items: [
          { text: 'CSS Transitions过渡', link: '/Part10-动画与交互/01-CSS-Transitions过渡' },
          { text: 'CSS Animations动画', link: '/Part10-动画与交互/02-CSS-Animations动画' },
          { text: 'React与CSS动画结合', link: '/Part10-动画与交互/03-React与CSS动画结合' },
          { text: 'Framer Motion入门', link: '/Part10-动画与交互/04-Framer-Motion入门' },
          { text: '动画变体Variants', link: '/Part10-动画与交互/05-动画变体(Variants)' },
          { text: '页面过渡动画', link: '/Part10-动画与交互/06-页面过渡动画' },
          { text: '手势识别', link: '/Part10-动画与交互/07-手势识别' },
          { text: '布局动画', link: '/Part10-动画与交互/08-布局动画(Layout-Animations)' },
          { text: 'React Spring物理动画', link: '/Part10-动画与交互/09-React-Spring物理动画' },
          { text: 'React Spring高级应用', link: '/Part10-动画与交互/10-React-Spring高级应用' },
          { text: 'React DnD拖拽', link: '/Part10-动画与交互/11-React-DnD拖拽' },
          { text: 'dnd-kit现代拖拽', link: '/Part10-动画与交互/12-dnd-kit现代拖拽' },
          { text: '拖拽排序实战', link: '/Part10-动画与交互/13-拖拽排序实战' },
          { text: 'react-use-gesture手势库', link: '/Part10-动画与交互/14-react-use-gesture手势库' },
          { text: 'react-intersection-observer滚动监听', link: '/Part10-动画与交互/15-react-intersection-observer滚动监听' },
        ]
      },
      {
        text: 'Part 11 - 测试与质量保障',
        collapsed: true,
        items: [
          { text: 'Jest测试框架', link: '/Part11-测试与质量保障/01-Jest测试框架' },
          { text: 'React Testing Library组件测试', link: '/Part11-测试与质量保障/02-React-Testing-Library组件测试' },
          { text: '测试用例编写规范', link: '/Part11-测试与质量保障/03-测试用例编写规范' },
          { text: 'Mock数据与函数', link: '/Part11-测试与质量保障/04-Mock数据与函数' },
          { text: '异步测试', link: '/Part11-测试与质量保障/05-异步测试' },
          { text: '测试覆盖率', link: '/Part11-测试与质量保障/06-测试覆盖率' },
          { text: '集成测试策略', link: '/Part11-测试与质量保障/07-集成测试策略' },
          { text: 'API Mock (MSW)', link: '/Part11-测试与质量保障/08-API-Mock(MSW)' },
          { text: 'Playwright E2E测试', link: '/Part11-测试与质量保障/09-Playwright-E2E测试' },
          { text: 'Cypress E2E测试', link: '/Part11-测试与质量保障/10-Cypress-E2E测试' },
          { text: 'E2E测试最佳实践', link: '/Part11-测试与质量保障/11-E2E测试最佳实践' },
          { text: 'ESLint配置与规则', link: '/Part11-测试与质量保障/12-ESLint配置与规则' },
          { text: 'Prettier代码格式化', link: '/Part11-测试与质量保障/13-Prettier代码格式化' },
          { text: 'React 19 ESLint插件更新', link: '/Part11-测试与质量保障/14-React-19-ESLint插件更新' },
          { text: 'Husky Git Hooks', link: '/Part11-测试与质量保障/15-Husky-Git-Hooks' },
          { text: 'Lint Staged增量检查', link: '/Part11-测试与质量保障/16-Lint-Staged增量检查' },
          { text: 'Commitlint提交规范', link: '/Part11-测试与质量保障/17-Commitlint提交规范' },
          { text: 'TypeScript基础语法', link: '/Part11-测试与质量保障/18-TypeScript基础语法' },
          { text: 'React与TypeScript集成', link: '/Part11-测试与质量保障/19-React与TypeScript集成' },
          { text: 'Props类型定义', link: '/Part11-测试与质量保障/20-Props类型定义' },
          { text: 'Hooks类型定义', link: '/Part11-测试与质量保障/21-Hooks类型定义' },
          { text: '泛型组件', link: '/Part11-测试与质量保障/22-泛型组件' },
          { text: 'TypeScript最佳实践', link: '/Part11-测试与质量保障/23-TypeScript最佳实践' },
        ]
      },
      {
        text: 'Part 12 - 全栈框架',
        collapsed: true,
        items: [
          { text: 'Next.js简介与安装', link: '/Part12-全栈框架/01-Next.js简介与安装' },
          { text: 'App Router路由系统', link: '/Part12-全栈框架/02-App-Router路由系统' },
          { text: 'Server Components服务端组件', link: '/Part12-全栈框架/03-Server-Components服务端组件' },
          { text: 'Client Components客户端组件', link: '/Part12-全栈框架/04-Client-Components客户端组件' },
          { text: 'Server Actions服务端操作', link: '/Part12-全栈框架/05-Server-Actions服务端操作' },
          { text: 'Data Fetching数据获取', link: '/Part12-全栈框架/06-Data-Fetching数据获取' },
          { text: '动态路由与参数', link: '/Part12-全栈框架/07-动态路由与参数' },
          { text: 'API Routes接口开发', link: '/Part12-全栈框架/08-API-Routes接口开发' },
          { text: '中间件Middleware', link: '/Part12-全栈框架/09-中间件(Middleware)' },
          { text: '静态生成SSG', link: '/Part12-全栈框架/10-静态生成(SSG)' },
          { text: '服务端渲染SSR', link: '/Part12-全栈框架/11-服务端渲染(SSR)' },
          { text: '增量静态再生成ISR', link: '/Part12-全栈框架/12-增量静态再生成(ISR)' },
          { text: '流式渲染Streaming', link: '/Part12-全栈框架/13-流式渲染(Streaming)' },
          { text: '图片优化next-image', link: '/Part12-全栈框架/14-图片优化(next-image)' },
          { text: '字体优化next-font', link: '/Part12-全栈框架/15-字体优化(next-font)' },
          { text: 'Metadata SEO优化', link: '/Part12-全栈框架/16-Metadata-SEO优化' },
          { text: '部署与优化', link: '/Part12-全栈框架/17-部署与优化' },
          { text: 'Remix框架概述', link: '/Part12-全栈框架/18-Remix框架概述' },
          { text: 'Remix路由与Loader', link: '/Part12-全栈框架/19-Remix路由与Loader' },
          { text: 'Remix Action表单处理', link: '/Part12-全栈框架/20-Remix-Action表单处理' },
          { text: 'Remix错误处理', link: '/Part12-全栈框架/21-Remix错误处理' },
          { text: 'Astro静态网站生成', link: '/Part12-全栈框架/22-Astro静态网站生成' },
          { text: 'Astro Islands架构', link: '/Part12-全栈框架/23-Astro-Islands架构' },
          { text: 'Next.js vs Remix vs Astro', link: '/Part12-全栈框架/24-Next.js-vs-Remix-vs-Astro' },
          { text: '全栈框架选型指南', link: '/Part12-全栈框架/25-全栈框架选型指南' },
        ]
      },
      {
        text: 'Part 13 - 构建与工程化',
        collapsed: true,
        items: [
          { text: 'Vite现代构建工具', link: '/Part13-构建与工程化/01-Vite现代构建工具' },
          { text: 'Vite配置与插件', link: '/Part13-构建与工程化/02-Vite配置与插件' },
          { text: 'Webpack配置(备选)', link: '/Part13-构建与工程化/03-Webpack配置(备选)' },
          { text: 'Rollup打包库', link: '/Part13-构建与工程化/04-Rollup打包库' },
          { text: '环境变量管理', link: '/Part13-构建与工程化/05-环境变量管理' },
          { text: '开发环境与生产环境区分', link: '/Part13-构建与工程化/06-开发环境与生产环境区分' },
          { text: '多环境配置', link: '/Part13-构建与工程化/07-多环境配置' },
          { text: '代码分割策略', link: '/Part13-构建与工程化/08-代码分割策略' },
          { text: '懒加载与预加载', link: '/Part13-构建与工程化/09-懒加载与预加载' },
          { text: 'CDN配置', link: '/Part13-构建与工程化/10-CDN配置' },
          { text: 'Gzip压缩', link: '/Part13-构建与工程化/11-Gzip压缩' },
          { text: '缓存策略', link: '/Part13-构建与工程化/12-缓存策略' },
          { text: 'Monorepo概念', link: '/Part13-构建与工程化/13-Monorepo概念' },
          { text: 'Turborepo使用', link: '/Part13-构建与工程化/14-Turborepo使用' },
          { text: 'pnpm workspace', link: '/Part13-构建与工程化/15-pnpm-workspace' },
          { text: 'Nx工具链', link: '/Part13-构建与工程化/16-Nx工具链' },
          { text: 'GitHub Actions自动化', link: '/Part13-构建与工程化/17-GitHub-Actions自动化' },
          { text: '自动化测试流程', link: '/Part13-构建与工程化/18-自动化测试流程' },
          { text: '自动化部署', link: '/Part13-构建与工程化/19-自动化部署' },
          { text: 'Vercel部署', link: '/Part13-构建与工程化/20-Vercel部署' },
          { text: 'Netlify部署', link: '/Part13-构建与工程化/21-Netlify部署' },
          { text: 'Docker容器化', link: '/Part13-构建与工程化/22-Docker容器化' },
          { text: 'Nginx配置', link: '/Part13-构建与工程化/23-Nginx配置' },
        ]
      },
      {
        text: 'Part 14 - 安全与SEO',
        collapsed: true,
        items: [
          { text: 'XSS跨站脚本攻击防护', link: '/Part14-安全与SEO/01-XSS跨站脚本攻击防护' },
          { text: 'CSRF跨站请求伪造防护', link: '/Part14-安全与SEO/02-CSRF跨站请求伪造防护' },
          { text: '内容安全策略CSP', link: '/Part14-安全与SEO/03-内容安全策略(CSP)' },
          { text: 'HTTPS与SSL证书', link: '/Part14-安全与SEO/04-HTTPS与SSL证书' },
          { text: 'JWT认证原理', link: '/Part14-安全与SEO/05-JWT认证原理' },
          { text: 'OAuth 2.0授权', link: '/Part14-安全与SEO/06-OAuth-2.0授权' },
          { text: '第三方登录集成', link: '/Part14-安全与SEO/07-第三方登录集成' },
          { text: '权限控制RBAC', link: '/Part14-安全与SEO/08-权限控制(RBAC)' },
          { text: 'SEO基础知识', link: '/Part14-安全与SEO/09-SEO基础知识' },
          { text: 'Meta标签优化', link: '/Part14-安全与SEO/10-Meta标签优化' },
          { text: 'OpenGraph与Twitter Cards', link: '/Part14-安全与SEO/11-OpenGraph与Twitter-Cards' },
          { text: '结构化数据Schema.org', link: '/Part14-安全与SEO/12-结构化数据(Schema.org)' },
          { text: 'Sitemap生成', link: '/Part14-安全与SEO/13-Sitemap生成' },
          { text: 'Robots.txt配置', link: '/Part14-安全与SEO/14-Robots.txt配置' },
          { text: 'SSR与SEO', link: '/Part14-安全与SEO/15-SSR与SEO' },
        ]
      },
      {
        text: 'Part 15 - 国际化与可访问性',
        collapsed: true,
        items: [
          { text: '国际化概念', link: '/Part15-国际化与可访问性/01-国际化概念' },
          { text: 'react-i18next使用', link: '/Part15-国际化与可访问性/02-react-i18next使用' },
          { text: 'React Intl使用', link: '/Part15-国际化与可访问性/03-React-Intl使用' },
          { text: '语言切换实现', link: '/Part15-国际化与可访问性/04-语言切换实现' },
          { text: '时区与日期处理', link: '/Part15-国际化与可访问性/05-时区与日期处理' },
          { text: '数字与货币格式化', link: '/Part15-国际化与可访问性/06-数字与货币格式化' },
          { text: 'ARIA无障碍规范', link: '/Part15-国际化与可访问性/07-ARIA无障碍规范' },
          { text: '语义化HTML', link: '/Part15-国际化与可访问性/08-语义化HTML' },
          { text: '键盘导航优化', link: '/Part15-国际化与可访问性/09-键盘导航优化' },
          { text: '屏幕阅读器适配', link: '/Part15-国际化与可访问性/10-屏幕阅读器适配' },
          { text: '颜色对比度优化', link: '/Part15-国际化与可访问性/11-颜色对比度优化' },
          { text: 'Focus焦点管理', link: '/Part15-国际化与可访问性/12-Focus焦点管理' },
          { text: 'react-aria无障碍库', link: '/Part15-国际化与可访问性/13-react-aria无障碍库' },
        ]
      },
      {
        text: 'Part 16 - 移动端与跨平台',
        collapsed: true,
        items: [
          { text: '响应式布局基础', link: '/Part16-移动端与跨平台/01-响应式布局基础' },
          { text: 'Flexbox布局', link: '/Part16-移动端与跨平台/02-Flexbox布局' },
          { text: 'Grid网格布局', link: '/Part16-移动端与跨平台/03-Grid网格布局' },
          { text: '媒体查询', link: '/Part16-移动端与跨平台/04-媒体查询' },
          { text: '移动端适配方案', link: '/Part16-移动端与跨平台/05-移动端适配方案(rem-vw)' },
          { text: 'PWA渐进式Web应用', link: '/Part16-移动端与跨平台/06-PWA渐进式Web应用' },
          { text: 'Service Worker离线缓存', link: '/Part16-移动端与跨平台/07-Service-Worker离线缓存' },
          { text: 'Web App Manifest', link: '/Part16-移动端与跨平台/08-Web-App-Manifest' },
          { text: '推送通知', link: '/Part16-移动端与跨平台/09-推送通知' },
          { text: 'React Native入门', link: '/Part16-移动端与跨平台/10-React-Native入门' },
          { text: 'React Native组件', link: '/Part16-移动端与跨平台/11-React-Native组件' },
          { text: 'React Native导航', link: '/Part16-移动端与跨平台/12-React-Native导航' },
          { text: 'React与React Native代码复用', link: '/Part16-移动端与跨平台/13-React与React-Native代码复用' },
          { text: 'Capacitor混合开发', link: '/Part16-移动端与跨平台/14-Capacitor混合开发' },
          { text: 'Ionic框架', link: '/Part16-移动端与跨平台/15-Ionic框架' },
        ]
      },
      {
        text: 'Part 17 - 面试突破',
        collapsed: true,
        items: [
          { text: 'Virtual DOM与Diff算法', link: '/Part17-面试突破/01-Virtual-DOM与Diff算法' },
          { text: 'Virtual DOM手写实现', link: '/Part17-面试突破/02-Virtual-DOM手写实现' },
          { text: 'Fiber架构深度解析', link: '/Part17-面试突破/03-Fiber架构深度解析' },
          { text: 'Fiber调度原理', link: '/Part17-面试突破/04-Fiber调度原理' },
          { text: '合成事件系统原理', link: '/Part17-面试突破/05-合成事件系统原理' },
          { text: '事件委托机制', link: '/Part17-面试突破/06-事件委托机制' },
          { text: 'Hooks链表结构详解', link: '/Part17-面试突破/07-Hooks链表结构详解' },
          { text: 'useState手写实现', link: '/Part17-面试突破/08-useState手写实现' },
          { text: 'useEffect手写实现', link: '/Part17-面试突破/09-useEffect手写实现' },
          { text: 'useMemo useCallback手写实现', link: '/Part17-面试突破/10-useMemo-useCallback手写实现' },
          { text: 'useReducer手写实现', link: '/Part17-面试突破/11-useReducer手写实现' },
          { text: 'React 19新特性总结', link: '/Part17-面试突破/12-React-19新特性总结' },
          { text: 'Server Components原理', link: '/Part17-面试突破/13-Server-Components原理' },
          { text: 'use() Hook原理', link: '/Part17-面试突破/14-use()Hook原理' },
          { text: 'React Compiler原理', link: '/Part17-面试突破/15-React-Compiler原理' },
          { text: '性能优化策略总结', link: '/Part17-面试突破/16-性能优化策略总结' },
          { text: '常见性能问题与解决', link: '/Part17-面试突破/17-常见性能问题与解决' },
          { text: '渲染优化案例分析', link: '/Part17-面试突破/18-渲染优化案例分析' },
          { text: 'Redux原理与中间件', link: '/Part17-面试突破/19-Redux原理与中间件' },
          { text: 'Context与Redux对比', link: '/Part17-面试突破/20-Context与Redux对比' },
          { text: '状态管理方案选型', link: '/Part17-面试突破/21-状态管理方案选型' },
          { text: '高频场景题汇总', link: '/Part17-面试突破/22-高频场景题汇总' },
          { text: '系统设计题', link: '/Part17-面试突破/23-系统设计题(Todo-聊天-后台)' },
          { text: '算法题', link: '/Part17-面试突破/24-算法题(React特色)' },
          { text: '100道高频React面试题', link: '/Part17-面试突破/25-100道高频React面试题' },
          { text: 'React 19专属面试题', link: '/Part17-面试突破/26-React-19专属面试题' },
          { text: '手写题集锦', link: '/Part17-面试突破/27-手写题集锦' },
        ]
      },
      {
        text: 'Part 18 - 调试与最佳实践',
        collapsed: true,
        items: [
          { text: 'React DevTools完全指南', link: '/Part18-调试与最佳实践/01-React-DevTools完全指南' },
          { text: 'Chrome DevTools调试', link: '/Part18-调试与最佳实践/02-Chrome-DevTools调试' },
          { text: 'VS Code调试配置', link: '/Part18-调试与最佳实践/03-VS-Code调试配置' },
          { text: '网络请求调试', link: '/Part18-调试与最佳实践/04-网络请求调试' },
          { text: '状态更新错误与解决', link: '/Part18-调试与最佳实践/05-状态更新错误与解决' },
          { text: 'useEffect常见错误', link: '/Part18-调试与最佳实践/06-useEffect常见错误' },
          { text: '闭包陷阱问题', link: '/Part18-调试与最佳实践/07-闭包陷阱问题' },
          { text: '内存泄漏识别与修复', link: '/Part18-调试与最佳实践/08-内存泄漏识别与修复' },
          { text: '渲染性能问题排查', link: '/Part18-调试与最佳实践/09-渲染性能问题排查' },
          { text: '错误边界深入', link: '/Part18-调试与最佳实践/10-错误边界深入' },
          { text: '错误上报系统搭建', link: '/Part18-调试与最佳实践/11-错误上报系统搭建' },
          { text: '代码组织规范', link: '/Part18-调试与最佳实践/12-代码组织规范' },
          { text: '文件命名规范', link: '/Part18-调试与最佳实践/13-文件命名规范' },
          { text: '组件设计原则', link: '/Part18-调试与最佳实践/14-组件设计原则' },
          { text: 'Hooks使用最佳实践', link: '/Part18-调试与最佳实践/15-Hooks使用最佳实践' },
          { text: '性能优化清单', link: '/Part18-调试与最佳实践/16-性能优化清单' },
          { text: '安全编码规范', link: '/Part18-调试与最佳实践/17-安全编码规范' },
          { text: '可维护性原则', link: '/Part18-调试与最佳实践/18-可维护性原则' },
          { text: '严格模式使用', link: '/Part18-调试与最佳实践/19-严格模式使用' },
          { text: '严格模式检查项', link: '/Part18-调试与最佳实践/20-严格模式检查项' },
        ]
      },
      {
        text: '附录与速查',
        collapsed: true,
        items: [
          { text: 'Hooks API对照表', link: '/附录与速查/API速查/Hooks-API对照表' },
          { text: 'React 19完整API速查表', link: '/附录与速查/API速查/React-19-完整API速查表' },
          { text: '常用第三方库速查', link: '/附录与速查/API速查/常用第三方库速查' },
          { text: '生命周期对照表', link: '/附录与速查/API速查/生命周期对照表' },
          { text: 'VS Code插件推荐', link: '/附录与速查/工具推荐/VS-Code插件推荐' },
          { text: '开发工具推荐', link: '/附录与速查/工具推荐/开发工具推荐(IDE-插件-扩展)' },
          { text: '生态系统工具全景图', link: '/附录与速查/工具推荐/生态系统工具全景图' },
          { text: 'React 19更新历史', link: '/附录与速查/更新日志/React-19更新历史' },
          { text: '未来特性预览', link: '/附录与速查/更新日志/未来特性预览' },
          { text: '生态系统更新追踪', link: '/附录与速查/更新日志/生态系统更新追踪' },
        ]
      },
    ],
    socialLinks: [
      { icon: 'github', link: 'https://github.com/YPYT1/awesome_react' }
    ],
    footer: {
      message: '基于 MIT 许可发布',
      copyright: 'Copyright © 2025 React 19 完全指南'
    },
    outline: {
      level: [2, 3]
    }
  },
  markdown: {
    lineNumbers: true
  }
})
